

Parameters:
  Name: 
    type: String
    default: charlie-test-rds-restore-point-in-time

Resources:
  CFNS3:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Ref Name

Outputs:
  S3ARN:
    Value:  !GetAtt CFNS3.Arn
    Description: S3 ARN
